version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: encrypt
          command: |
            rm -rf /var/cache/apk/*
            rm -rf /tmp/
            apk update
            apk add openssl
            tar -zc config > config.tgz
            openssl aes-256-cbc -e -in config.tgz -out config.tgz.enc -S ${SRCKEY:0:10} -k $SRCKEY

      - run:
          name: Build application Docker image
          command: |
            docker build -t app .

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag app scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
              docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            fi
     # build the application image
      # - run:
      #     name: Build Docker Image scbd/drupal-code-base:{$CIRCLE_BRANCH}
      #     command: docker build -t scbd/drupal-code-base:$CIRCLE_BRANCH .

#
#   deploy-job:
#     machine: true
#
#     steps:
#       - checkout
#
#      # build the application image
#       - run:
#           name: Push Docker Image scbd/drupal-code-base:$CIRCLE_BRANCH to Dockerhub
#           command: |
#             docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#             docker tag output scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
#             docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
#
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build-job
#       - deploy-job:
#           requires:
#             - build-job
#           # filters:
#           #   branches:
#           #     only:
#           #       - stg
#           #       - dev
