version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4c:f3:df:b8:c0:91:7f:b1:71:d3:14:c4:04:d4:15:19"
      - checkout
      - setup_remote_docker

      # - restore_cache:
      #     keys:
      #       - v1-{{ .Branch }}
      #     paths:
      #       - /caches/app.tar
      - run:
          name: submodule update & encrypt
          command: |
            rm -rf /var/cache/apk/*
            apk update
            apk add openssl
            git submodule status
            git submodule sync
            git submodule update --init --remote
            git submodule status
            tar -zc config > config.tgz
            openssl aes-256-cbc -e -in config.tgz -out config.tgz.enc -S ${SRCKEY:0:10} -k $SRCKEY
            rm config.tgz
            rm -rf config
            ls -al

      # - run:
      #     name: Load Docker image layer cache
      #     command: |
      #       set +o pipefail
      #       docker load -i /caches/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            ls -al
            docker build  -f Dockerfile-encrypted -t app .

      # - run:
      #     name: Save Docker image layer cache
      #     command: |
      #       mkdir -p /caches
      #       docker save -o /caches/app.tar app
      # - save_cache:
      #     key: v1-{{ .Branch }}-{{ epoch }}
      #     paths:
      #       - /caches/app.tar

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag app scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
              docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            fi
            if [ "${CIRCLE_BRANCH}" == "stg" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag app scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
              docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            fi


#
#   deploy-job:
#     machine: true
#
#     steps:
#       - checkout
#
#      # build the application image
#       - run:
#           name: Push Docker Image scbd/drupal-code-base:$CIRCLE_BRANCH to Dockerhub
#           command: |
#             docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#             docker tag output scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
#             docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
#
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build-job
#       - deploy-job:
#           requires:
#             - build-job
#           # filters:
#           #   branches:
#           #     only:
#           #       - stg
#           #       - dev
